project:
  type: website

website:
  title: "ratatui-template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: part1.qmd
        text: "Part 1: Basics"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
