project:
  type: website

website:
  title: "ratatui-template"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents: auto

filters:
  - quarto
  - line-highlight

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
