name: docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  MDBOOK-ADMONISH-VERSION: v1.7.0
  MDBOOK-CATPPUCCIN-VERSION: v0.1.1
  MDBOOK-LINKCHECK-VERSION: v0.1.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-plugins
        run: |
          mkdir mdbook-admonish
          curl -LsSL https://github.com/tommilligan/mdbook-admonish/releases/download/${{ env.MDBOOK-ADMONISH-VERSION }}/mdbook-admonish-${{ env.MDBOOK-ADMONISH-VERSION }}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-admonish
          echo `pwd`/mdbook-admonish >> $GITHUB_PATH

          mkdir mdbook-catppuccin
          curl -LsSL https://github.com/catppuccin/mdBook/releases/download/${{ env.MDBOOK-CATPPUCCIN-VERSION }}/mdbook-catppuccin-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-catppuccin
          echo `pwd`/mdbook-catppuccin >> $GITHUB_PATH

          curl -LsSf https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/${{ env.MDBOOK-LINKCHECK-VERSION }}/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip
          unzip mdbook-linkcheck.zip -d mdbook-linkcheck
          chmod +x mdbook-linkcheck/mdbook-linkcheck
          echo `pwd`/mdbook-linkcheck >> $GITHUB_PATH

      - name: Install mdbook-svgbob2
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.3.0 mdbook-svgbob2

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with mdbook
        run: mdbook build book

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book/book

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
