name: docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-catppuccin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.1.1 mdbook-catppuccin

      - name: Install mdbook-admonish
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 1.9.0 mdbook-admonish

      - name: Install mdbook-svgbob2
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.3.0 mdbook-svgbob2

      - name: Install mdbook-linkcheck
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.7.7 mdbook-linkcheck

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with mdbook
        run: mdbook build book

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book/book

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
