name: docs

on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      # Cache cargo registry and target directories
      - name: Cache Cargo registry and target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install mdbook-admonish
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 1.9.0 mdbook-admonish

      - name: Install mdbook-svgbob2
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.3.0 mdbook-svgbob2

      - name: Install mdbook-linkcheck
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.7.7 mdbook-linkcheck

      - name: Build with mdbook
        run: mdbook build book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
